_BASE_: [
  'yolov5u_l_300e_coco.yml',
]


YOLOv5:
  backbone: CSPDarkNet
  neck: YOLOCSPPAN
  yolo_head: YOLOv8Head_rect
  post_process: ~

YOLOv8Head_rect:
  fpn_strides: [8, 16, 32]
  loss_weight: {class: 0.5, iou: 7.5, dfl: 1.5}
  assigner:
    name: TaskAlignedAssigner
    topk: 10
    alpha: 0.5
    beta: 6.0
  nms:
    name: MultiClassNMS
    nms_top_k: 3000
    keep_top_k: 300
    score_threshold: 0.001
    nms_threshold: 0.7


input_height: &input_height 640
input_width: &input_width 640
input_size: &input_size [*input_height, *input_width]
EvalReader:
  sample_transforms:
    - Decode: {}
    - YOLOv5KeepRatioResize: {target_size: *input_size, batch_shapes: True, size_divisor: 32, extra_pad_ratio: 0.5}
    - LetterResize: {scale: *input_size, pad_val: 144, allow_scale_up: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 1 # rect eval only support bs=1
